CREATE DATABASE IF NOT EXISTS minesweeper;
USE minesweeper;

CREATE TABLE IF NOT EXISTS easy (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, scores VARCHAR(255));
CREATE TABLE IF NOT EXISTS hard (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, scores VARCHAR(255));
CREATE TABLE IF NOT EXISTS ludicrous (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, scores VARCHAR(255));